version: '3'
services:
#mssql docker
  erestoran-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - erestorannet

  erestoran-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eRestoran=Server=erestoran-sql,1433;Database=IB170116;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 49947:80
    networks:
      - erestorannet
    links:
      - erestoran-sql
    depends_on:
      - erestoran-sql

networks:
  erestorannet:
    driver: bridge       